[package]
name = "happy_hardware_interface"
version = "0.1.0"
edition = "2021"

[lib]
name = "happy_hardware_interface"
crate-type = ["staticlib"]

[dependencies]
serialport = "4.2.2"
thiserror = "1.0.58"
log = "0.4.21"
